from abc import ABC, abstractmethod

class Repository(ABC):
    @abstractmethod
    def create_ticket(self, ticket): ...
    @abstractmethod
    def get_ticket(self, ticket_id): ...
    @abstractmethod
    def update_ticket(self, ticket_id, data): ...
    @abstractmethod
    def delete_ticket(self, ticket_id): ...
    @abstractmethod
    def list_tickets(self): ...
    @abstractmethod
    def create_message(self, message): ...
    @abstractmethod
    def list_messages(self, ticket_id): ...
    @abstractmethod
    def mark_has_admin_reply(self, ticket_id): ...
    @abstractmethod
    def get_admin_user(self, username): ...
    @abstractmethod
    def create_attachment(self, ticket_id, stored_path, orig_name, mime, size): ...
